### ISSUE TITLE
Getting "bad request" on execution 

### ISSUE THREAD

**Issue by jatinsinghalsg** [directus-community/migration-tool#12]
Getting following on execution

```
MacBook-Pro directus-migration-tool % node index.js
✨ Migrating http://localhost:8090/project (v8) to http://localhost:8055 (v9)...
  ❯ Migrating Schema
    ✔ Downloading Schema
    ❯ Creating Collections
      ✖ test_collection
        → Request failed with status code 400
      Migrating Relations
    Migration Files
    Migrating Users
    Migrating Data
Error: Request failed with status code 400
    at createError (/Users/jatinsinghal/Documents/projects/canopy/directus-migration-tool/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/jatinsinghal/Documents/projects/canopy/directus-migration-tool/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/jatinsinghal/Documents/projects/canopy/directus-migration-tool/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    url: '/collections',
    method: 'post',
    data: '{"collection":"test_collection","meta":{"note":null,"hidden":false,"singleton":false,"translations":null,"sort_field":null},"schema":{},"fields":[{"field":"id","type":"integer","meta":{"note":"","interface":null,"translation":null,"readonly":false,"hidden":true,"width":"full"},"schema":{"has_auto_increment":true,"default_value":null,"is_primary_key":true,"is_nullable":false,"max_length":"10","numeric_precision":"10","numeric_scale":null}},{"field":"status","type":"string","meta":{"note":"","interface":"dropdown","translation":null,"readonly":false,"hidden":false,"width":"full"},"schema":{"has_auto_increment":false,"default_value":"draft","is_primary_key":false,"is_nullable":false,"max_length":"20","numeric_precision":"20","numeric_scale":null}},{"field":"sort","type":"integer","meta":{"note":"","interface":"numeric","translation":null,"readonly":false,"hidden":true,"width":"full"},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":"10","numeric_precision":"10","numeric_scale":null}},{"field":"owner","type":"uuid","meta":{"note":"","interface":"user","translation":null,"readonly":true,"hidden":true,"width":"full","special":["user-created"]},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":"10","numeric_precision":"10","numeric_scale":null}},{"field":"created_on","type":"timestamp","meta":{"note":"","interface":"datetime","translation":null,"readonly":true,"hidden":true,"width":"full","special":["date-created"]},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":null,"numeric_precision":null,"numeric_scale":null}},{"field":"text_1","type":"string","meta":{"note":"","interface":"text-input","translation":null,"readonly":false,"hidden":false,"width":"full"},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":"200","numeric_precision":"200","numeric_scale":null}},{"field":"json_1","type":"text","meta":{"note":"","interface":"json","translation":null,"readonly":false,"hidden":false,"width":"full","special":["json"]},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":null,"numeric_precision":null,"numeric_scale":null}}]}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json;charset=utf-8',
      Authorization: 'Bearer qsQJHjDW8SXwBZqkHTtLp4htq2xj3SfN',
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 2360
    },
    baseURL: 'http://localhost:8055',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'localhost',
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(async_id_symbol)]: 89,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'POST /collections HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json;charset=utf-8\r\n' +
      'Authorization: Bearer qsQJHjDW8SXwBZqkHTtLp4htq2xj3SfN\r\n' +
      'User-Agent: axios/0.21.1\r\n' +
      'Content-Length: 2360\r\n' +
      'Host: localhost:8055\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/collections',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'http://localhost:8055/collections',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'localhost',
    protocol: 'http:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 2360,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'http://localhost:8055/collections',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      authorization: [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array]
    }
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: {
      'x-powered-by': 'Directus',
      vary: 'Origin',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '113',
      etag: 'W/"71-YartklZ00JpQjys820QI6m1/qgU"',
      date: 'Mon, 05 Apr 2021 10:47:13 GMT',
      connection: 'close'
    },
    config: {
      url: '/collections',
      method: 'post',
      data: '{"collection":"test_collection","meta":{"note":null,"hidden":false,"singleton":false,"translations":null,"sort_field":null},"schema":{},"fields":[{"field":"id","type":"integer","meta":{"note":"","interface":null,"translation":null,"readonly":false,"hidden":true,"width":"full"},"schema":{"has_auto_increment":true,"default_value":null,"is_primary_key":true,"is_nullable":false,"max_length":"10","numeric_precision":"10","numeric_scale":null}},{"field":"status","type":"string","meta":{"note":"","interface":"dropdown","translation":null,"readonly":false,"hidden":false,"width":"full"},"schema":{"has_auto_increment":false,"default_value":"draft","is_primary_key":false,"is_nullable":false,"max_length":"20","numeric_precision":"20","numeric_scale":null}},{"field":"sort","type":"integer","meta":{"note":"","interface":"numeric","translation":null,"readonly":false,"hidden":true,"width":"full"},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":"10","numeric_precision":"10","numeric_scale":null}},{"field":"owner","type":"uuid","meta":{"note":"","interface":"user","translation":null,"readonly":true,"hidden":true,"width":"full","special":["user-created"]},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":"10","numeric_precision":"10","numeric_scale":null}},{"field":"created_on","type":"timestamp","meta":{"note":"","interface":"datetime","translation":null,"readonly":true,"hidden":true,"width":"full","special":["date-created"]},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":null,"numeric_precision":null,"numeric_scale":null}},{"field":"text_1","type":"string","meta":{"note":"","interface":"text-input","translation":null,"readonly":false,"hidden":false,"width":"full"},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":"200","numeric_precision":"200","numeric_scale":null}},{"field":"json_1","type":"text","meta":{"note":"","interface":"json","translation":null,"readonly":false,"hidden":false,"width":"full","special":["json"]},"schema":{"has_auto_increment":false,"default_value":null,"is_primary_key":false,"is_nullable":true,"max_length":null,"numeric_precision":null,"numeric_scale":null}}]}',
      headers: [Object],
      baseURL: 'http://localhost:8055',
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'POST /collections HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json;charset=utf-8\r\n' +
        'Authorization: Bearer qsQJHjDW8SXwBZqkHTtLp4htq2xj3SfN\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Content-Length: 2360\r\n' +
        'Host: localhost:8055\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/collections',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { errors: [Array] }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON],
  context: [Object: null prototype] { collections: [ [Object] ] }
}
```

**Comment by miguelsimoes** [comment]
Can you also paste the log from Directus as well? Should a better error message regarding what is wrong with the request.

**Comment by jatinsinghalsg** [comment]
@miguelsimoes as far as I can see, following stdout I get from Docker

```
directus    | 10:46:47 ✨ request completed POST 400 /collections 71ms
directus    | 10:47:13 ✨ request completed POST 400 /collections 16ms
```
Is there anywhere else I can find the logs?

**Comment by miguelsimoes** [comment]
Can you ensure you have the `LOG_LEVEL=debug` on your container (see https://docs.directus.io/reference/environment-variables/#general), please? 

Also, I was able to create the collection by directly calling my Directus v9 with the data payload and the creation was successful.

**Comment by jatinsinghalsg** [comment]
@miguelsimoes got the issue

```
07:27:32 🐛 Collection "test_collection" already exists.
```

As an improvement, we can add better error messages like **duplicate collection, duplicate user** etc. I am closing this ticket for now.
