### ISSUE TITLE
Migration is Failing with 404

### ISSUE THREAD

**Issue by arpijoy** [directus-community/migration-tool#25]
Migrating the Test Directus8 to Directus9 is failing. Has anyone used this tool successfully?

```
$ node index.js
✨ Migrating https://taxonomy-directus-service.test.xxx.com (v8) to https://taxonomy-directus-service.dev.xxx.com (v9)...
  ❯ Migrating Schema
    ✖ Downloading Schema
      → Request failed with status code 404
      Creating Collections
      Migrating Relations
    Migration Files
    Migrating Users
    Migrating Data
Error: Request failed with status code 404
    at createError (/workdir/migration/migration-tool/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/workdir/migration/migration-tool/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/workdir/migration/migration-tool/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (node:events:388:22)
    at endReadableNT (node:internal/streams/readable:1295:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  config: {
    url: '/collections',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlNTY0N2NkLWFhNTEtNDJmNy05YWExLTBjYzM2NGUwNDFjMiIsImlhdCI6MTYyMDY3NDE4OCwiZXhwIjoxNjIwNjc1MDg4fQ.5--203VXNU1kdKV7HUnWm6cmQ1GkmzYweYlmLAuh988',
      Cookie: 'directus--session=undefined',
      'User-Agent': 'axios/0.21.1'
    },
    baseURL: 'https://taxonomy-directus-service.test.xxx.com/',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'taxonomy-directus-service.test.xxx.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'taxonomy-directus-service.test.xxx.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 56,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET /collections HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJlNTY0N2NkLWFhNTEtNDJmNy05YWExLTBjYzM2NGUwNDFjMiIsImlhdCI6MTYyMDY3NDE4OCwiZXhwIjoxNjIwNjc1MDg4fQ.5--203VXNU1kdKV7HUnWm6cmQ1GkmzYweYlmLAuh988\r\n' +
      'Cookie: directus--session=undefined\r\n' +
      'User-Agent: axios/0.21.1\r\n' +
      'Host: taxonomy-directus-service.test.xxx.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/collections',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://taxonomy-directus-service.test.xxx.com/collections',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 14,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'taxonomy-directus-service.test.xxx.com',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://taxonomy-directus-service.test.xxx.com/collections',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      authorization: [Array],
      cookie: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 404,
    statusText: 'Not Found',
    headers: {
      date: 'Mon, 10 May 2021 19:18:39 GMT',
      'content-type': 'application/json',
      'content-length': '42',
      connection: 'close',
      server: 'Apache/2.4.38 (Debian)',
      'x-powered-by': 'PHP/7.3.20',
      'access-control-allow-origin': '*'
    },
    config: {
      url: '/collections',
      method: 'get',
      headers: [Object],
      baseURL: 'https://taxonomy-directus-service.test.xxx.com/',
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /collections HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Authorization: Bearer FhNTEtNDJmNy05YWExLTBjYzM2NGUwNDFjMiIsImlhdCI6MTYyMDY3NDE4OCwiZXhwIjoxNjIwNjc1MDg4fQ.5--203VXNU1kdKV7HUnWm6cmQ1GkmzYweYlmLAuh988\r\n' +
        'Cookie: directus--session=undefined\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: taxonomy-directus-service.test.xxx.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/collections',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'taxonomy-directus-service.test.xxx.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { error: [Object] }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON],
  context: [Object: null prototype] { skipCollections: [] }
}
```

@rijkvanzanten any thoughts on how to resolve?

**Comment by rijkvanzanten** [comment]
> Has anyone used this tool successfully?

Yes, many times

> @rijkvanzanten any thoughts on how to resolve?

No need to tag me, I get notified of all activity under the `directus` and `directus-community` orgs 👍🏻 

---

What is the configuration you're using? Did you set `V8_PROJECT_NAME` ?

**Comment by arpijoy** [comment]
> You can't have a v8 instance without a project name. In case you're using the default, the project name is `_` 👍🏻

Yes, you are right, I used `_` as the project name when I saw the Schema.js trying to fetch data from undefined. I am able to see the schema collections from the browser; but the tool still fails with 401

**Comment by arpijoy** [comment]
> Did you set `V8_TOKEN` and `V9_TOKEN` with tokens that have admin access?

Yes, both users are Admin Roles in the Directus 8 and 9. 
https://taxonomy-directus-service.test.xxx.com/_/collections -> I can see the entire JSON collections schema

**Comment by arpijoy** [comment]
The issue is not resolved, but I see the status Closed; I am still experiencing issue

**Comment by rijkvanzanten** [comment]
Are you sure your project is `_` then? Looks like your project is named `Directus` in this URL 🤔
