### ISSUE TITLE
TypeError: Cannot read property '4' of undefined

### ISSUE THREAD

**Issue by arpijoy** [directus-community/migration-tool#27]
The data migration is failing with the following error:
 ❯ Inserting Data
      ✖ text_classification
        → Cannot read property '4' of undefined
        ..
    Migrating Users
    Migration Files
TypeError: Cannot read property '4' of undefined
    at file:///Users/acho/workdir/migration/migration-tool/tasks/data.js:87:24
    at Array.map (<anonymous>)
    at insertBatch (file:///Users/acho/workdir/migration/migration-tool/tasks/data.js:83:32)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Task.task (file:///Users/acho/workdir/migration/migration-tool/tasks/data.js:49:4) {
  context: [Object: null prototype] {
    skipCollections: [
      'testing'
    ],

**Comment by samuelstein** [comment]
same issue here with the latest version of the migration tool
