### ISSUE TITLE
Migrating translations : What about the parsing of languages code (ex: "fr", "en") to languages ids ?

### ISSUE THREAD

**Issue by stouch** [directus-community/migration-tool#42]
Hello,

In V8, to translate the contents I made something like that (in my memory it was a good practice) : 

page (id, translations (translations with id<->page_translations.page))
page_translations (id, page (int), language_code (language))

So, when I finally succeeded to import my data to the V9 with the migration-tool, I noticed that my collections kept this old schema, and there didn't had any conversion to the new schema with language_id etc of Directus v9.

So, I don't have any idea of how I'm going to restore all my translations because now they do not appear at all (blank space below "Translations" for exemple in each of my page items).

Is it something that someone is working on ?

**Comment by rijkvanzanten** [comment]
> So, I don't have any idea of how I'm going to restore all my translations because now they do not appear at all (blank space below "Translations" for exemple in each of my page items).

Any errors in the app dev tools? What did the schema look like exactly in v8, and what is the end result in v9?

**Comment by stouch** [comment]
Before :

<img width="861" alt="before_page_translations" src="https://user-images.githubusercontent.com/17531455/128361823-9f212ca1-296e-4f91-8826-899c865f6ba8.png">
<img width="850" alt="before_pages" src="https://user-images.githubusercontent.com/17531455/128361824-1fd99223-f95a-4683-a3c9-256dd698921d.png">

After : 

<img width="931" alt="after_page_translations" src="https://user-images.githubusercontent.com/17531455/128361818-57194f9d-0949-4a90-8478-1439a04f6087.png">
<img width="912" alt="after_pages" src="https://user-images.githubusercontent.com/17531455/128361822-f2a889ac-a18e-4ed6-8a16-ec42b502cadc.png">


And I've finally that :  
<img width="857" alt="Capture d’écran 2021-08-05 à 17 29 12" src="https://user-images.githubusercontent.com/17531455/128377359-998194fb-e992-4515-8971-680d6e34193f.png">

**Comment by stouch** [comment]
If you need anything else, do not hesitate to ask me

**Comment by skuhnow** [comment]
I have the same problem. Migrated, but no working translations. 
I tried these steps so far

1. create `languages` table (created a `test` collection and an translation field)
2. set `special` and `interface` to `translations` inside your `directus_fields` table for your main table 
3. remove the original, empty `translations` field in your main table 
4. create `directus_relations` relations (used the relation from my test-collection from step 1)
5. inserted all old language codes (in v8 it was `de` or `en`) in my `languages` table so that i can create a real foreign key in step 6.
6. create a FK in my translation table. also used my test_translations collection as a template

Still no Translation selector, but "at least" I get an error 

TypeError: Cannot read properties of undefined (reading 'find')
    at Proxy.SY (index.edc993a6.entry.js:519:9000)
    at m5 (vendor.59c25dbe.js:2:22303)

Not very helpful so far
