### ISSUE TITLE
Migration failed on `Migrating Relations`

### ISSUE THREAD

**Issue by artur-shaik** [directus-community/migration-tool#53]
Trying to migrate and have this errors. Any ideas where and what I should debug?

```
  ❯ Migrating Relations
    ✔ Get v8 Relations
    ✔ Saving Relations context
    ✖ Migrating Relations
      → Request failed with status code 500
      Saving Relations context
    Migrating Data
    Save final context
Error: Request failed with status code 500
    at createError (/home/ash/Soft/directus-migration-tool/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/ash/Soft/directus-migration-tool/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/ash/Soft/directus-migration-tool/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  config: {
    url: '/relations',
    method: 'post',
    data: '{"meta":{"many_collection":"we_offer","many_field":"title","one_collection":"about","one_field":"we_offer","junction_field":null},"field":"title","collection":"we_offer","related_collection":"about","schema":null}',
```

Server logs:
```
21:26:54 🚨 error alter table "we_offer" add constraint "we_offer_title_fore
ign" foreign key ("title") references "about" ("id") - foreign key constrain
t "we_offer_title_foreign" cannot be implemented
error: alter table "we_offer" add constraint "we_offer_title_foreign" foreig
n key ("title") references "about" ("id") - foreign key constraint "we_offer
_title_foreign" cannot be implemented
    at Parser.parseErrorMessage (/home/ash/projects/shaini/shaini.kg/directu
s-shaini/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/ash/projects/shaini/shaini.kg/directus-sha
ini/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/ash/projects/shaini/shaini.kg/directus-shaini/nod
e_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/ash/projects/shaini/shaini.kg/directus-shai
ni/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
21:26:54 ✨ request errored POST 500 /relations 23ms

```

**Comment by rijkvanzanten** [comment]
Looks like it's trying to setup a relationship between "we_offer.title" and "about.id". I'm assuming that title is a string, and id is an integer. Could you check in your v8s relations table to see if there's something funky in there?

**Comment by artur-shaik** [comment]
I'm actually don't know why it tries to relate by `title` column, here is what I have. Collection `about` has O2M relation to `we_offer`:

![Screenshot_20210903_153236](https://user-images.githubusercontent.com/4862907/131984204-af1bfb51-9f51-429c-8fe6-51b741673bf4.png)
![Screenshot_20210903_153308](https://user-images.githubusercontent.com/4862907/131984210-c979b71d-8472-483e-8aaf-ae673a89e07b.png)

`title` field used only in preview option in collection `about`:
![image](https://user-images.githubusercontent.com/4862907/131984408-12dd918a-0ebb-4120-8a19-de42f0d0dcee.png)

**Comment by artur-shaik** [comment]
And here what I have in database:
```
MariaDB [directus]> select * from directus_relations;
+----+--------------------------------+--------------------+----------------------+-----------------+--------------------+
| id | collection_many                | field_many         | collection_one       | field_one       | junction_field     |
+----+--------------------------------+--------------------+----------------------+-----------------+--------------------+
| 20 | we_offer                       | title              | about                | we_offer        | NULL               |
| 21 | we_offer                       | about              | about                | we_offer        | NULL               |
```

**Comment by rijkvanzanten** [comment]
@artur-shaik That last example does in fact have that wrong relation! See id = `20`, that has "title" listed as the foreign key field 🤔

**Comment by artur-shaik** [comment]
Yeah, something wrong here. So I fixed it by replacing `title` with `id` and moved on. Thank you.
