### ISSUE TITLE
Migration stops at repeater options

### ISSUE THREAD

**Issue by richardt3** [directus-community/migration-tool#58]
Using latest v8 and v9 RC93. I think this is a repeater field issue 

```
TypeError: fieldDetails.options.fields.map is not a function
    at migrateFieldOptions (file:///home/support/migration-tool/tasks/schema.js:84:43)
    at file:///home/support/migration-tool/tasks/schema.js:203:22
    at Array.map (<anonymous>)
    at Task.task (file:///home/support/migration-tool/tasks/schema.js:177:48)
    at /home/support/migration-tool/node_modules/listr/lib/task.js:167:30
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  context: [Object: null prototype] {
    completedSteps: {
      schema: true,
      collections: false,
      files: false,
      roles: false,
      users: false,
      relationsv8: false,
      relations: false,
      data: false,
      completed: false
    },

```

**Comment by rijkvanzanten** [comment]
Hmm yeah this line shouldn't try mapping then:

https://github.com/directus-community/migration-tool/blob/db3d18dc4d5c18104271488f7fc364178a0396aa/tasks/schema.js#L84

as in v8 that fields config is an object with keys 🤔

**Comment by MyIgel** [comment]
As i have the same problem, is there anything that i can debug further to fix the problem?

**Comment by richardt3** [comment]
Thank You

**Comment by eduardoPinto12** [comment]
I'm having this exact same error (_**context: [Object: null prototype]**_) on data migration step from v8 (latest) to v9 (latest) on a collection with a repeater,

Error: Data migration failed. Check directus logs for most insight.
    at insertBatch (file:///home/migration-tool/tasks/data.js:218:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Task.task (file:///home/migration-tool/tasks/data.js:138:4) {
  context: [Object: null prototype] {
    completedSteps: {
      schema: true,
      collections: true,
      files: true,
      roles: true,
      users: true,
      relationsv8: true,
      relations: true,
      data: false,
      completed: false
    },
    
Does anyone have any idea what's going on?
