### ISSUE TITLE
"Not a function" error when Creating Collections

### ISSUE THREAD

**Issue by mattbisme** [directus-community/migration-tool#65]
Hello, 

When running the migration tool, everything seems to connect correctly, but then it fails during the `Migrating Schema → Creating Collections` phase. Collections produce a `(details.length || "").split is not a function` error. I tried excluding the `menu_cats` collection (this would be the easiest to reproduce manually), but then the `menu_items` collection threw the same error.

For full context, the v8 database is MySQL and the v9 is SQLite. I suspect that shouldn't make a difference, but figured that I would mention it anyway. Any guidance would be appreciated.

Thanks!

```
Loading context
✨ Loaded context succesfully
  ✔ Loading context
  ❯ Migrating Schema
    ✔ Downloading Schema
    ✔ Saving schema context
    ❯ Creating Collections
      ✖ menu_cats
        → (details.length || "").split is not a function
        menu_items
        menu_item_prices
      Saving collections context
    Migration Files
    Migrating Users
    Migrating Relations
    Migrating Data
    Save final context
TypeError: (details.length || "").split is not a function
    at file:///Users/mattbisme/Sites/_global/directus_migration/migration-tool/tasks/schema.js:235:44
    at Array.map (<anonymous>)
    at Task.task (file:///Users/mattbisme/Sites/_global/directus_migration/migration-tool/tasks/schema.js:197:48)
    at /Users/mattbisme/Sites/_global/directus_migration/migration-tool/node_modules/listr/lib/task.js:167:30 {
  context: [Object: null prototype] {
    completedSteps: {
      schema: true,
      collections: false,
      files: false,
      roles: false,
      users: false,
      relationsv8: false,
      relations: false,
      data: false,
      completed: false
    },
    collectionsV9: [],
    skipCollections: [],
    collections: [ [Object], [Object], [Object] ]
  }
}
```

**Comment by mattbisme** [comment]
@rijkvanzanten Thank you for pointing that out. I've played around with this a bit and found that changing the two lines with a `split()` to `((details.length) ? details.length.toString() : "").split(",")[0] || null` results in a successful migration.

…or so it seems. This could be a separate issue, but now when making simple changes (such as the Display template) to M2O fields results in an `Invalid foreign key` error. Upon inspecting the new database, I can't find anything that seems off in my custom tables. 

Maybe Directus is expecting something that's a bit different from what was imported? Ultimately, I had to remove foreign key restraints, recreate the fields that had relationships, and then reimport the lost data. This does feel like an unrelated issue, but I don't think I understand the inner workings of Directus well enough to speak confidently.

I will say that the migration tool *still* got the data from MySQL to SQLite more efficiently, and with less trouble, than other tools that I've used, haha.

```json
{
  "errors": [
    {
      "message": "Invalid foreign key.",
      "extensions": {
        "code": "INVALID_FOREIGN_KEY"
      }
    }
  ]
}
```
