### ISSUE TITLE
Error while migrating relations - 

### ISSUE THREAD

**Issue by OmairMedia** [directus-community/migration-tool#76]
yes , i have followed these steps : 

1) i have created a empty database in mysql 
2) import sql dumb files one-by-one
3)  ran v8 directus project and got user auth token by api 
4) ran v9 new fresh project and got user auth token by api 
5) ran migration-tool , its now giving error on migrating relations

![image](https://user-images.githubusercontent.com/79204165/191705173-15b16a1a-a371-4734-8ae4-a14981429244.png)

v8 Database : 
![image](https://user-images.githubusercontent.com/79204165/191705338-554fa7aa-ecc6-4323-9677-4cdc65797b6e.png)

Error Log File While Migration: 

    V9 =>
    /relations
    undefined
    undefined
    V9 <=
    400
    {
    "errors": [
        {
            "message": "Field \"output_destination_id\" in collection \"output_destination_deal_pool\" already has an associated relationship",
            "extensions": {
                "code": "INVALID_PAYLOAD"
            }
        }
    ]
}
    
Error: 
    V9 =>
    /relations
    undefined
    undefined
    V9 <=
    400
    {
    "errors": [
        {
            "message": "Field \"output_destination_id\" in collection \"output_destination_deal_pool\" already has an associated relationship",
            "extensions": {
                "code": "INVALID_PAYLOAD"
            }
        }
    ]
}
    
    at file:///C:/Omair%20Folder/Office%20Projects/Directus%20Database%20Migration%20Project/migration-tool/api.js:41:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async migrateRelationsData (file:///C:/Omair%20Folder/Office%20Projects/Directus%20Database%20Migration%20Project/migration-tool/tasks/relations.js:116:3)

**Comment by customautosys** [comment]
I get this: Cannot read properties of undefined (reading 'reduce')
