### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by benediktkeller** [directus-community/migration-tool#8]
Hey guys,
thanks for the migration tool. Unfortunately I get the error "SyntaxError: Unexpected identifier" when starting, although listr was installed via npm ci. Do you have an idea what could be wrong?

Output starting with `node index.js`:
```
import Listr from "listr";
       ^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by rijkvanzanten** [comment]
Node started supporting ESM in Node 13 and up. I'm assuming your CI is running < Node 12 ?

**Comment by benediktkeller** [comment]
Oh, you are right. I downgraded node last month for another project. That's it, thanks! :+1::innocent:
